interface RuntimeVersionConfig {
  APP_VERSION?: string;
  GIT_SHA?: string;
  BUILD_TIME?: string;
}

const runtimeVersion: RuntimeVersionConfig =
  (typeof window !== "undefined" &&
    (window as unknown as { __APP_CONFIG__?: RuntimeVersionConfig }).__APP_CONFIG__) ||
  {};

/**
 * Public version metadata.
 *
 * Resolution order:
 *   1. Runtime config.js rendered from Cloud Run env.
 *   2. Build-time Vite env generated by vite.config.ts.
 *   3. Safe local defaults.
 *
 * ⚠️ PUBLIC — this ships to the browser. No secrets.
 */
export const APP_VERSION: string =
  runtimeVersion.APP_VERSION || import.meta.env.VITE_APP_VERSION || "dev";

export const GIT_SHA: string =
  runtimeVersion.GIT_SHA || import.meta.env.VITE_GIT_SHA || "local";

export const BUILD_TIME: string =
  runtimeVersion.BUILD_TIME || import.meta.env.VITE_BUILD_TIME || new Date().toISOString();

/** Short SHA for display (first 7 chars). */
export const GIT_SHA_SHORT: string = GIT_SHA.slice(0, 7);

/** Structured version info for console/debug. */
export const VERSION_INFO = {
  version: APP_VERSION,
  gitSha: GIT_SHA,
  gitShaShort: GIT_SHA_SHORT,
  buildTime: BUILD_TIME,
} as const;

// Log version to console on app boot (non-intrusive).
if (typeof window !== "undefined") {
  // eslint-disable-next-line no-console
  console.info(
    "%c[SkillBridge]%c v%s (%s) built %s",
    "color:#2563eb;font-weight:bold",
    "color:inherit",
    APP_VERSION,
    GIT_SHA_SHORT,
    BUILD_TIME,
  );
}
