// pages/Learning.tsx — UPDATED
// Changes from original:
// 1. Added "Generate" tab → navigates to /roadmap-generator
// 2. Shows AI-generated badge when roadmap is generated by the backend AI service
// 3. Passes roadmap store data to child views

import { useState } from "react";
import { useNavigate } from "react-router-dom";
import Layout from "@/components/layout/Layout";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import {
  Calendar, LayoutGrid, List, Info, BookOpen, ClipboardCheck, Sparkles,
} from "lucide-react";
import { cn } from "@/lib/utils";
import {
  LearningSidebar, OverviewView, GridRoadmapView, ListRoadmapView, AssessmentView,
} from "@/components/learning";
import AIChatWidget from "@/components/dashboard/AIChatWidget";
import { useRoadmapStore } from "@/components/learning/roadmap-store";

type ViewMode = "overview" | "grid" | "list" | "assessment";

const VIEW_TABS: { value: ViewMode; label: string; icon: React.ElementType }[] = [
  { value: "overview",    label: "Today",      icon: Calendar },
  { value: "grid",        label: "Overview",   icon: LayoutGrid },
  { value: "list",        label: "List view",  icon: List },
  { value: "assessment",  label: "Assessment", icon: ClipboardCheck },
];

export default function Learning() {
  const navigate = useNavigate();
  const [activeView, setActiveView] = useState<ViewMode>("overview");
  const { isAIGenerated, generatedRoadmap, clearRoadmap } = useRoadmapStore();

  return (
    <Layout hideFooter>
      <div className="flex justify-center px-4 md:px-6">
        <div className="flex flex-col lg:flex-row gap-6 w-full max-w-[1200px] py-6">

          {/* ─── Main Content ─── */}
          <div className="flex-1 min-w-0 space-y-5">

            {/* Header */}
            <header className="flex flex-col sm:flex-row sm:items-start sm:justify-between gap-4">
              <div>
                <div className="flex items-center gap-2 mb-1 flex-wrap">
                  <h1 className="text-2xl font-bold text-slate-900 leading-tight">
                    {isAIGenerated && generatedRoadmap
                      ? generatedRoadmap.title
                      : "Frontend Developer Path"}
                  </h1>
                  {isAIGenerated && (
                    <Badge className="bg-primary/10 text-primary border border-primary/20 text-xs font-semibold flex items-center gap-1">
                      <Sparkles className="w-3 h-3" /> AI Generated
                    </Badge>
                  )}
                  <button className="w-5 h-5 text-slate-400 hover:text-primary">
                    <Info className="w-5 h-5" />
                  </button>
                </div>
                <p className="text-slate-500 text-sm">
                  {isAIGenerated && generatedRoadmap
                    ? `${generatedRoadmap.totalWeeks} weeks · ${generatedRoadmap.totalHours}h · ${generatedRoadmap.courses.length} courses`
                    : "Track your roadmap and weekly learning progress"}
                </p>
              </div>

              <div className="flex items-center gap-2 flex-shrink-0">
                {isAIGenerated && (
                  <Button
                    variant="ghost"
                    size="sm"
                    onClick={clearRoadmap}
                    className="text-xs text-slate-400 hover:text-slate-700 rounded-full"
                  >
                    Reset to demo
                  </Button>
                )}
                {/* ✅ Generate button → goes to roadmap generator */}
                <Button
                  onClick={() => navigate("/roadmap-generator")}
                  className="rounded-full text-sm font-semibold gap-2 shadow-sm"
                  variant={isAIGenerated ? "outline" : "default"}
                >
                  <Sparkles className="w-4 h-4" />
                  {isAIGenerated ? "Regenerate" : "Generate Roadmap"}
                </Button>
                <Button
                  variant="outline"
                  className="rounded-full border-slate-200 text-sm font-semibold text-slate-700"
                >
                  <BookOpen className="w-4 h-4 mr-2" /> View Syllabus
                </Button>
              </div>
            </header>

            {/* AI Advice banner (shows when AI generated) */}
            {isAIGenerated && generatedRoadmap?.aiAdvice && (
              <div className="flex items-start gap-3 p-4 bg-amber-50 border border-amber-100 rounded-xl animate-in fade-in duration-500">
                <Sparkles className="w-4 h-4 text-amber-500 flex-shrink-0 mt-0.5" />
                <p className="text-sm text-amber-800 leading-relaxed">
                  <span className="font-semibold">AI Tip: </span>
                  {generatedRoadmap.aiAdvice.split("\n")[0]}
                </p>
              </div>
            )}

            {/* View Tabs */}
            <div className="flex items-center gap-1 p-1 bg-slate-100 rounded-xl w-fit">
              {VIEW_TABS.map(tab => {
                const Icon = tab.icon;
                const isActive = activeView === tab.value;
                return (
                  <button
                    key={tab.value}
                    onClick={() => setActiveView(tab.value)}
                    className={cn(
                      "flex items-center gap-2 px-4 py-2 rounded-lg text-sm font-semibold transition-all",
                      isActive ? "bg-white text-slate-900 shadow-sm" : "text-slate-500 hover:text-slate-700"
                    )}
                  >
                    <Icon className="w-4 h-4" />
                    {tab.label}
                  </button>
                );
              })}
            </div>

            {/* Content */}
            <div className="animate-in fade-in duration-300">
              {activeView === "overview"   && <OverviewView />}
              {activeView === "grid"       && <GridRoadmapView />}
              {activeView === "list"       && <ListRoadmapView />}
              {activeView === "assessment" && <AssessmentView />}
            </div>
          </div>

          {/* ─── Sidebar ─── */}
          <div className="w-full lg:w-[280px] flex-shrink-0">
            <div className="lg:sticky lg:top-24 mt-6 lg:mt-0">
              <LearningSidebar />
            </div>
          </div>
        </div>
      </div>

      <AIChatWidget />
    </Layout>
  );
}
