import { MapPin, Plus, ShieldCheck, Sparkles, Trash2 } from "lucide-react";
import { Link } from "react-router-dom";
import { IT_ROLES } from "@/constants/it-roles";
import type { JobLocationDto, JobPublishReadiness, JobSkillDto } from "@/types/jobs";
import type { BusinessJobEditorStep, BusinessJobFormState, BusinessJobStepErrors } from "@/pages/business/business-job-form";
import { dateInputToEndOfDayIso, splitLines } from "@/pages/business/business-job-form";
import { Field, SelectInput, TextArea, TextInput } from "./JobEditorPrimitives";

const EMPLOYMENT_TYPES = ["FULL_TIME", "PART_TIME", "INTERNSHIP", "CONTRACT", "FREELANCE"] as const;
const EXPERIENCE_LEVELS = ["INTERN", "FRESHER", "JUNIOR", "MIDDLE", "SENIOR", "LEAD"] as const;
const WORK_MODES = ["ONSITE", "HYBRID", "REMOTE"] as const;

type Change = <K extends keyof BusinessJobFormState>(field: K, value: BusinessJobFormState[K]) => void;

export function BasicStep({ form, errors, disabled, onChange }: { form: BusinessJobFormState; errors: BusinessJobStepErrors; disabled: boolean; onChange: Change }) {
  return <section className="space-y-5" aria-labelledby="job-step-basic">
    <header><p className="text-sm font-semibold text-slate-900" id="job-step-basic">Basic details</p><p className="text-sm text-slate-500">Fields marked required are needed before you continue.</p></header>
    <div className="grid gap-5 sm:grid-cols-2">
      <Field label="Job title" error={errors.title} className="sm:col-span-2"><TextInput required disabled={disabled} hasError={Boolean(errors.title)} value={form.title} onChange={(event) => onChange("title", event.target.value)} /></Field>
      <Field label="Role" error={errors.roleCode}><SelectInput required disabled={disabled} hasError={Boolean(errors.roleCode)} value={form.roleCode} onChange={(event) => onChange("roleCode", event.target.value)}><option value="">Choose a role</option>{IT_ROLES.map((role) => <option key={role.code} value={role.code}>{role.label}</option>)}</SelectInput></Field>
      <Field label="Openings" optional error={errors.openingsCount}><TextInput disabled={disabled} inputMode="numeric" placeholder="1" hasError={Boolean(errors.openingsCount)} value={form.openingsCount} onChange={(event) => onChange("openingsCount", event.target.value)} /></Field>
      <Field label="Employment type" optional><SelectInput disabled={disabled} value={form.employmentType} onChange={(event) => onChange("employmentType", event.target.value as BusinessJobFormState["employmentType"])}><option value="">Not specified</option>{EMPLOYMENT_TYPES.map((type) => <option key={type}>{type}</option>)}</SelectInput></Field>
      <Field label="Work mode" optional><SelectInput disabled={disabled} value={form.workMode} onChange={(event) => onChange("workMode", event.target.value as BusinessJobFormState["workMode"])}><option value="">Not specified</option>{WORK_MODES.map((mode) => <option key={mode}>{mode}</option>)}</SelectInput></Field>
      <Field label="Experience level" optional><SelectInput disabled={disabled} value={form.experienceLevel} onChange={(event) => onChange("experienceLevel", event.target.value as BusinessJobFormState["experienceLevel"])}><option value="">Not specified</option>{EXPERIENCE_LEVELS.map((level) => <option key={level}>{level}</option>)}</SelectInput></Field>
    </div>
    <details className="rounded-lg border border-slate-200 p-4"><summary className="cursor-pointer text-sm font-medium text-slate-700">Advanced compensation and experience</summary><div className="mt-4 grid gap-4 sm:grid-cols-2">
      <Field label="Minimum years" optional error={errors.experience}><TextInput disabled={disabled} inputMode="decimal" value={form.minYearsExperience} onChange={(event) => onChange("minYearsExperience", event.target.value)} /></Field>
      <Field label="Maximum years" optional><TextInput disabled={disabled} inputMode="decimal" value={form.maxYearsExperience} onChange={(event) => onChange("maxYearsExperience", event.target.value)} /></Field>
      <Field label="Minimum salary" optional error={errors.salary}><TextInput disabled={disabled} inputMode="decimal" value={form.salaryMin} onChange={(event) => onChange("salaryMin", event.target.value)} /></Field>
      <Field label="Maximum salary" optional><TextInput disabled={disabled} inputMode="decimal" value={form.salaryMax} onChange={(event) => onChange("salaryMax", event.target.value)} /></Field>
      <Field label="Currency" optional><TextInput disabled={disabled} value={form.currency} onChange={(event) => onChange("currency", event.target.value)} /></Field>
      <Field label="Salary period" optional><SelectInput disabled={disabled} value={form.salaryPeriod} onChange={(event) => onChange("salaryPeriod", event.target.value as BusinessJobFormState["salaryPeriod"])}><option value="">Not specified</option><option value="MONTH">Monthly</option><option value="YEAR">Yearly</option></SelectInput></Field>
    </div><div className="mt-4 flex flex-wrap gap-5 text-sm text-slate-700"><label><input disabled={disabled} checked={form.salaryVisible} type="checkbox" onChange={(event) => onChange("salaryVisible", event.target.checked)} /> Display salary</label><label><input disabled={disabled} checked={form.salaryNegotiable} type="checkbox" onChange={(event) => onChange("salaryNegotiable", event.target.checked)} /> Negotiable</label></div></details>
  </section>;
}

export function ContentStep({ form, errors, disabled, deadlineBounds, onChange, onAddLocation, onRemoveLocation, onLocationChange }: { form: BusinessJobFormState; errors: BusinessJobStepErrors; disabled: boolean; deadlineBounds: { min: string; max: string }; onChange: Change; onAddLocation: () => void; onRemoveLocation: (index: number) => void; onLocationChange: (index: number, field: keyof JobLocationDto, value: JobLocationDto[keyof JobLocationDto]) => void }) {
  return <section className="space-y-5" aria-labelledby="job-step-content"><header><p className="text-sm font-semibold text-slate-900" id="job-step-content">Content, deadline and hiring location</p><p className="text-sm text-slate-500">Remote jobs still need a hiring city and two-letter country code. Address is optional.</p></header>
    <div className="grid gap-5 sm:grid-cols-2"><Field label="Application deadline" error={errors.applicationDeadline}><TextInput required disabled={disabled} type="date" min={deadlineBounds.min} max={deadlineBounds.max} hasError={Boolean(errors.applicationDeadline)} value={form.applicationDeadline ? form.applicationDeadline.slice(0, 10) : ""} onChange={(event) => onChange("applicationDeadline", dateInputToEndOfDayIso(event.target.value))} /></Field><Field label="Working time" optional><TextInput disabled={disabled} value={form.workingTime} onChange={(event) => onChange("workingTime", event.target.value)} /></Field></div>
    <Field label="Summary" error={errors.summary}><TextArea required disabled={disabled} hasError={Boolean(errors.summary)} value={form.summary} onChange={(event) => onChange("summary", event.target.value)} /></Field>
    <div className="grid gap-5 lg:grid-cols-2"><Field label="Responsibilities (one per line)" error={errors.responsibilities}><TextArea required disabled={disabled} hasError={Boolean(errors.responsibilities)} value={form.responsibilitiesText} onChange={(event) => onChange("responsibilitiesText", event.target.value)} /></Field><Field label="Requirements (one per line)" error={errors.requirements}><TextArea required disabled={disabled} hasError={Boolean(errors.requirements)} value={form.requirementsText} onChange={(event) => onChange("requirementsText", event.target.value)} /></Field></div>
    <details className="rounded-lg border border-slate-200 p-4"><summary className="cursor-pointer text-sm font-medium text-slate-700">Optional job content</summary><div className="mt-4 grid gap-4 lg:grid-cols-2"><Field label="Nice to have (one per line)" optional><TextArea disabled={disabled} value={form.niceToHaveText} onChange={(event) => onChange("niceToHaveText", event.target.value)} /></Field><Field label="Benefits (one per line)" optional><TextArea disabled={disabled} value={form.benefitsText} onChange={(event) => onChange("benefitsText", event.target.value)} /></Field><Field label="Interview process (one per line)" optional><TextArea disabled={disabled} value={form.interviewProcessText} onChange={(event) => onChange("interviewProcessText", event.target.value)} /></Field><Field label="Education level" optional><TextInput disabled={disabled} value={form.educationLevel} onChange={(event) => onChange("educationLevel", event.target.value)} /></Field></div></details>
    <div className="space-y-3"><div className="flex items-center justify-between"><div><p className="text-sm font-semibold text-slate-900">Hiring locations</p>{errors.locations ? <p className="text-[13px] text-red-600">{errors.locations}</p> : null}</div><button type="button" disabled={disabled} onClick={onAddLocation} className="inline-flex items-center gap-1 text-sm font-medium text-sky-700 disabled:opacity-50"><Plus size={15} /> Add location</button></div>{form.locations.map((location, index) => <div className="grid gap-3 rounded-lg border border-slate-200 p-3 sm:grid-cols-[1fr_1fr_2fr_auto]" key={`${index}-${location.cityCode}`}><Field label="City"><TextInput disabled={disabled} value={location.cityCode} onChange={(event) => onLocationChange(index, "cityCode", event.target.value)} /></Field><Field label="Country"><TextInput disabled={disabled} maxLength={2} value={location.countryCode} onChange={(event) => onLocationChange(index, "countryCode", event.target.value.toUpperCase())} /></Field><Field label="Address" optional><TextInput disabled={disabled} value={location.addressLine} onChange={(event) => onLocationChange(index, "addressLine", event.target.value)} /></Field><div className="flex items-end gap-2"><label className="pb-2 text-xs text-slate-600"><input type="radio" name="primary-location" checked={location.isPrimary} disabled={disabled} onChange={() => onLocationChange(index, "isPrimary", true)} /> Primary</label><button type="button" disabled={disabled} title="Remove location" className="pb-2 text-slate-500 hover:text-red-600" onClick={() => onRemoveLocation(index)}><Trash2 size={16} /></button></div></div>)}{form.locations.length === 0 ? <button type="button" disabled={disabled} onClick={onAddLocation} className="rounded-lg border border-dashed border-slate-300 p-4 text-left text-sm text-slate-500"><MapPin size={16} className="mb-1" />Add the first hiring location.</button> : null}</div>
  </section>;
}

export function SkillsStep({ skills, disabled, formDirty, skillsNeedRefresh, confirmedAt, extracting, confirming, onExtract, onConfirm, onChange, onRemove }: { skills: JobSkillDto[]; disabled: boolean; formDirty: boolean; skillsNeedRefresh: boolean; confirmedAt: string | null | undefined; extracting: boolean; confirming: boolean; onExtract: () => void; onConfirm: () => void; onChange: (index: number, field: keyof JobSkillDto, value: JobSkillDto[keyof JobSkillDto]) => void; onRemove: (index: number) => void }) {
  return <section className="space-y-5" aria-labelledby="job-step-skills"><header><p className="text-sm font-semibold text-slate-900" id="job-step-skills">Extract, review and confirm skills</p><p className="text-sm text-slate-500">Skills are generated from the saved job content. Review them before publishing.</p></header>{formDirty ? <p className="rounded-md bg-amber-50 p-3 text-sm text-amber-800">Save your content first. Extraction and publishing are unavailable while the form has unsaved edits.</p> : null}{skillsNeedRefresh ? <p className="rounded-md bg-amber-50 p-3 text-sm text-amber-800">Skills need a fresh extraction and confirmation before publishing.</p> : null}<button type="button" disabled={disabled || formDirty || extracting} onClick={onExtract} className="inline-flex items-center gap-2 rounded-md border border-slate-300 px-4 py-2 text-sm font-medium disabled:opacity-50"><Sparkles size={16} />{extracting ? "Extracting…" : "Extract skills"}</button>
    {skills.length ? <div className="space-y-3">{skills.map((skill, index) => <div key={skill.skillId} className="flex flex-wrap items-center justify-between gap-3 rounded-lg border border-slate-200 p-3"><div><p className="font-medium text-slate-900">{skill.canonicalName}</p>{skill.rawText ? <p className="text-xs text-slate-500">Found as: {skill.rawText}</p> : null}</div><div className="flex gap-2"><SelectInput disabled={disabled} value={skill.importance} onChange={(event) => onChange(index, "importance", event.target.value as JobSkillDto["importance"])}><option value="REQUIRED">Required</option><option value="NICE_TO_HAVE">Nice to have</option></SelectInput><SelectInput disabled={disabled} value={skill.minLevel ?? ""} onChange={(event) => onChange(index, "minLevel", event.target.value ? Number(event.target.value) as JobSkillDto["minLevel"] : null)}><option value="">Any level</option>{[1, 2, 3, 4, 5].map((level) => <option key={level} value={level}>Level {level}+</option>)}</SelectInput><button type="button" disabled={disabled} onClick={() => onRemove(index)} title="Remove skill" className="text-slate-500 hover:text-red-600"><Trash2 size={16} /></button></div></div>)}<button type="button" disabled={disabled || formDirty || !skills.length || confirming} onClick={onConfirm} className="inline-flex items-center gap-2 rounded-md bg-emerald-600 px-4 py-2 text-sm font-medium text-white disabled:opacity-50"><ShieldCheck size={16} />{confirming ? "Confirming…" : "Confirm skills"}</button>{confirmedAt && !skillsNeedRefresh ? <span className="ml-3 text-sm text-emerald-700">Confirmed</span> : null}</div> : <p className="text-sm text-slate-500">No skills extracted yet.</p>}</section>;
}

export function ReviewStep({ form, readiness, localBlockers, onBlocker, onCompanyProfile }: { form: BusinessJobFormState; readiness: JobPublishReadiness; localBlockers: JobPublishReadiness["blockers"]; onBlocker: (blocker: JobPublishReadiness["blockers"][number]) => void; onCompanyProfile: () => void }) {
  const blockers = [...localBlockers, ...readiness.blockers];
  const isCompanyBlocker = (blocker: JobPublishReadiness["blockers"][number]) => /company|profile/i.test(`${blocker.code} ${blocker.field}`);
  return <section className="space-y-5" aria-labelledby="job-step-review"><header><p className="text-sm font-semibold text-slate-900" id="job-step-review">Review, preview and publish</p><p className="text-sm text-slate-500">Preview uses your current form. Publishing uses the latest saved draft.</p></header><article className="rounded-xl border border-slate-200 bg-slate-50 p-5"><p className="text-lg font-semibold text-slate-900">{form.title || "Untitled job"}</p><p className="mt-1 text-sm text-slate-600">{form.roleCode || "No role selected"} · {form.workMode || "Work mode not specified"}</p><p className="mt-4 whitespace-pre-wrap text-sm text-slate-700">{form.summary || "No summary yet"}</p><div className="mt-4 grid gap-4 sm:grid-cols-2"><div><p className="text-xs font-semibold uppercase text-slate-500">Responsibilities</p><ul className="mt-1 list-disc pl-5 text-sm text-slate-700">{splitLines(form.responsibilitiesText).map((line) => <li key={line}>{line}</li>)}</ul></div><div><p className="text-xs font-semibold uppercase text-slate-500">Requirements</p><ul className="mt-1 list-disc pl-5 text-sm text-slate-700">{splitLines(form.requirementsText).map((line) => <li key={line}>{line}</li>)}</ul></div></div></article><section className={`rounded-lg border p-4 ${blockers.length ? "border-amber-200 bg-amber-50" : "border-emerald-200 bg-emerald-50"}`}><p className="font-medium text-slate-900">{blockers.length ? "Fix these before publishing" : "Ready to publish"}</p>{blockers.length ? <ul className="mt-2 space-y-2">{blockers.map((blocker, index) => <li key={`${blocker.code}-${blocker.field}-${index}`}>{isCompanyBlocker(blocker) ? <Link className="text-sm text-amber-900 underline" to="/business/profile" onClick={(event) => { event.preventDefault(); onCompanyProfile(); }}>{blocker.message}</Link> : <button type="button" className="text-left text-sm text-amber-900 underline" onClick={() => onBlocker(blocker)}>{blocker.message}</button>}</li>)}</ul> : null}</section></section>;
}

export const EDITOR_STEPS: Array<{ id: BusinessJobEditorStep; label: string }> = [{ id: "basic", label: "Basic" }, { id: "content", label: "Content & location" }, { id: "skills", label: "Skills" }, { id: "review", label: "Review & publish" }];
